"""
LLM Response Model
"""

from dataclasses import dataclass


@dataclass(slots=True)
class LLMResponse:
    """
    Response generated by the LLM.
    """

    answer: str
    source_chunks: list[str]